name: Build App

on:
    push:
        branches: [ci-testing]
    pull_request:

jobs:
    build:
        runs-on: windows-latest

        steps:
            # Step 1: Checkout repository
            - name: Checkout repository
              uses: actions/checkout@v4

            # Step 2: Download and extract program (example: 7zip portable zip)
            - name: Download portable 7zip
              run: |
                  Invoke-WebRequest -Uri "https://www.7-zip.org/a/7zr.exe" -OutFile "7zr.exe"
                  # just an example; replace with your program's .zip
                  Invoke-WebRequest -Uri "https://www.7-zip.org/a/7z2301-extra.7z" -OutFile "tool.7z"
                  mkdir "$env:USERPROFILE\tool"
                  .\7zr.exe x tool.7z -o"$env:USERPROFILE\tool" -y

            # Step 3: Add extracted folder to PATH
            - name: Add tool to PATH
              run: echo "$env:USERPROFILE\tool" >> $env:GITHUB_PATH

            # Step 4: Set up Node.js
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            # Step 5: Install dependencies
            - name: Install dependencies
              run: npm ci

            # Step 6: Download & process obb file
            - name: Download and preprocess extra file
              run: |
                  Invoke-WebRequest -Uri "https://example.com/extra.dat" -OutFile "extra.dat"
                  node scripts/preprocess.js extra.dat

            # Step 7: Run Node.js build script that uses the program
            - name: Run build script
              run: node scripts/build.js
